### ISSUE TITLE
multiple instances performance issue

### ISSUE THREAD

**Issue by jkufrin** [ksachdeva/angular2-swiper#1]
Are you going to get this loaded into NPM soon? I'm having trouble trying to get this component loaded into my site with the latest v0.4.0 RC1 code. I'm currently just using the v0.3.0 code. 

I'm also having performance issues when multiple instances are on the page, similar to Netflix.com type of layout. I have 20-30 instances on the page depending on the API call. When I restrict it to just 6, it runs much better. Are you aware of any performance issues like this?

**Comment by ksachdeva** [comment]
Not aware of it but then I have not used multiple instances. That said, not sure if this component will introduce such problems as it is a very simple wrapper on swiper. It would be best to re-create your scenario outside angular i.e. with just swiper library and see if the problem is there or not.
